# first we define our action name 
name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Composer Dependencies
        uses: php-actions/composer@v2
        with:
          php-version: 7.4  # Adjust as needed

      - name: Run PHPUnit Tests
        run: composer exec phpunit

  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: build-test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{secrets.EC2_SSH_KEY}}
          server-host: ${{secrets.REMOTE_HOST}}
          server-user: ${{secrets.REMOTE_USER}}
          local-folder: ./
          remote-folder: ${{secrets.TARGET}}

  composer:
    name: Run Composer Install on EC2 instance
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Execute Composer Install
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd ${{secrets.TARGET}}
            composer install
